IRFog.clear()
IRFog.setCell(3, 4, IRFog.State.EXPLORED)
assert(IRFog.getCell(3, 4) == IRFog.State.EXPLORED)
local cellOk = pcall(IRFog.setCell, 3, 4, 7)
assert(not cellOk)
assert(IRFog.getCell(3, 4) == IRFog.State.EXPLORED)
IRFog.revealRadius(0, 0, 2)
assert(IRFog.getCell(0, 0) == IRFog.State.VISIBLE)
IRFog.clear()
assert(IRFog.getCell(0, 0) == IRFog.State.UNEXPLORED)

IRFog.clearVisions()
IRFog.setVision(-10, 0, 4, 0, 3, 0.5, -1, 1)
IRFog.addVision(10, 0, 4, 0, 3, 0.5, -1, 1)
assert(IRFog.evalReveal(-10, 0, 3) == 1)
assert(IRFog.evalReveal(10, 0, 3) == 1)
assert(IRFog.evalReveal(0, 0, 3) == 0)
assert(IRFog.lineOfSight(-10, 0, 3, 10, 0, 3))

local before = IRFog.evalReveal(-10, 0, 3)
local ok = pcall(IRFog.addVision, 0, 0, "bad radius")
assert(not ok)
assert(IRFog.evalReveal(-10, 0, 3) == before)

fogSetupSelftestDone()
print("LUA-FOG-SETUP sources=2 centers=-10,0;10,0 PASS")
