// T-107 regression coverage: the codegen system path emits typed C++ tick
// bodies that match the EVAL register surface for the cases that map
// cleanly between them — canonical for-loop, math intrinsics, branches,
// excludes filter, and field-level column ops. Cases that require the
// runtime field-index API or sol::function bodies (T-103 hot-reload, mixed
// C++/Lua component archetypes, dynamic field names) stay in
// lua_system_register_test.cpp; per the architect plan those are EVAL-only
// and excluded from CODEGEN by design.
//
// The fixture .lua used to generate the included header is the sibling
// `lua_system_codegen_fixtures.lua`; both are processed by
// `cmake/lua_codegen` at build time via the `irreden_lua_codegen()` helper
// wired in `test/CMakeLists.txt`.

#include <gtest/gtest.h>

#include <irreden/ir_entity.hpp>
#include <irreden/ir_system.hpp>
#include <irreden/ir_time.hpp>
#include <irreden/script/lua_script.hpp>

#include <vector>

// Generated by cmake/lua_codegen from lua_system_codegen_fixtures.lua.
// Path is added to the include search list by irreden_lua_codegen().
#include "lua_system_codegen_fixtures.hpp"

namespace {

// LuaScript first so its sol::state outlives sol::function-bearing columns
// held by EntityManager (mirrors lua_component_register_test.cpp + T-106's
// component codegen test).
class LuaSystemCodegenTest : public testing::Test {
  protected:
    LuaSystemCodegenTest()
        : m_lua{}
        , m_entity_manager{}
        , m_system_manager{} {
        m_lua.bindLuaDrivenEcs();
        IRScript::CodegenRegistry::registerCodegenComponents(m_lua);
    }

    IRScript::LuaScript m_lua;
    IREntity::EntityManager m_entity_manager;
    IRSystem::SystemManager m_system_manager;
};

// ---- Canonical loop + column ops -----------------------------------------
//
// pos and vel are read-only (no write to CodegenSysPos between the at(i)
// binding and any subsequent read). The emitter should lower both to
// `const auto& pos` / `const auto& vel` rather than `auto` (copy). Verify
// in: build/test/codegen/lua_system_codegen_fixtures.hpp →
// createSystem_CodegenMove(). If the alias path silently regresses to copy,
// the fixture will show `auto pos` instead of `const auto& pos`.

TEST_F(LuaSystemCodegenTest, MovePositionByVelocityRoundTrip) {
    using IRComponents::C_CodegenSysPos;
    using IRComponents::C_CodegenSysVel;

    const auto e =
        IREntity::createEntity(C_CodegenSysPos(1.0f, 2.0f), C_CodegenSysVel(10.0f, 20.0f));

    const IRSystem::SystemId sys = IRScript::CodegenRegistry::createSystem_CodegenMove();
    EXPECT_LT(sys, m_system_manager.getSystemCount());
    EXPECT_STREQ(m_system_manager.getSystemName(sys).c_str(), "CodegenMove");

    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(e).x_, 11.0f);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(e).y_, 22.0f);
}

// ---- Math intrinsic via the whitelist ------------------------------------
//
// Asserts that `math.sin(...)` is routed through `IRMath::sin` (i.e. the
// codegen tool actually consulted the intrinsic table — a literal `0.0`
// in the Lua body would compile but would not match the wobble math).

TEST_F(LuaSystemCodegenTest, WobbleAppliesMathSinThroughIntrinsicWhitelist) {
    using IRComponents::C_CodegenSysPos;
    const float y = 1.5f;
    const auto e = IREntity::createEntity(C_CodegenSysPos(0.0f, y));

    const IRSystem::SystemId sys = IRScript::CodegenRegistry::createSystem_CodegenWobble();
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    // Expected: pos.x' = pos.x + sin(pos.y).
    const float expected = IRMath::sin(y);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(e).x_, expected);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(e).y_, y);
}

// ---- Branches preserve out-of-block locals -------------------------------
//
// The clamp body declares `local pos` inside the for-loop, then references
// it in the branch. Asserts the symbol-tracking + scope-snapshot logic in
// the emitter doesn't bleed inner-block locals out (or vice versa).

TEST_F(LuaSystemCodegenTest, ClampPositiveOnlyTouchesNegativeXEntities) {
    using IRComponents::C_CodegenSysPos;

    const auto eNeg = IREntity::createEntity(C_CodegenSysPos(-3.0f, 2.0f));
    const auto ePos = IREntity::createEntity(C_CodegenSysPos(5.0f, 7.0f));

    const IRSystem::SystemId sys = IRScript::CodegenRegistry::createSystem_CodegenClampPositive();
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(eNeg).x_, 0.0f);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(eNeg).y_, 2.0f);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(ePos).x_, 5.0f);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(ePos).y_, 7.0f);
}

// ---- Excludes filter materialised as IRSystem::Exclude<> ------------------

TEST_F(LuaSystemCodegenTest, ExcludesFilterDropsTaggedArchetype) {
    using IRComponents::C_CodegenSysPos;
    using IRComponents::C_CodegenSysSkip;

    const auto eKeep = IREntity::createEntity(C_CodegenSysPos(0.0f, 0.0f));
    const auto eSkip = IREntity::createEntity(C_CodegenSysPos(0.0f, 0.0f), C_CodegenSysSkip{});

    const IRSystem::SystemId sys = IRScript::CodegenRegistry::createSystem_CodegenAddOne();
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(eKeep).x_, 1.0f);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(eSkip).x_, 0.0f);
}

// ---- Field-level column ops (getField / setField) ------------------------

TEST_F(LuaSystemCodegenTest, DamageAppliesFieldGetAndFieldSet) {
    using IRComponents::C_CodegenSysHp;

    constexpr int kCount = 3;
    std::vector<IREntity::EntityId> entities;
    for (int i = 0; i < kCount; ++i) {
        entities.push_back(IREntity::createEntity(C_CodegenSysHp{}));
    }

    const IRSystem::SystemId sys = IRScript::CodegenRegistry::createSystem_CodegenDamage();
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    for (auto e : entities) {
        EXPECT_EQ(IREntity::getComponent<C_CodegenSysHp>(e).current_, 90);
        EXPECT_EQ(IREntity::getComponent<C_CodegenSysHp>(e).max_, 100);
    }
}

// ---- All codegen system create functions return distinct SystemIds --------
//
// Sanity that the systems registry helper (`registerCodegenSystems()`) is
// emitted and returns one SystemId per system declared in the fixture. The
// per-test create_System_X() above use the same machinery; this one
// asserts the registry-helper aggregates them in declared order without
// collisions.

TEST_F(LuaSystemCodegenTest, RegistryReturnsAllCodegenSystemIds) {
    auto ids = IRScript::CodegenRegistry::registerCodegenSystems();
    EXPECT_NE(ids.CodegenMove, ids.CodegenWobble);
    EXPECT_NE(ids.CodegenWobble, ids.CodegenClampPositive);
    EXPECT_NE(ids.CodegenClampPositive, ids.CodegenAddOne);
    EXPECT_NE(ids.CodegenAddOne, ids.CodegenDamage);
    EXPECT_NE(ids.CodegenDamage, ids.CodegenParallelInc);
    EXPECT_NE(ids.CodegenParallelInc, ids.CodegenReadAfterWrite);
    EXPECT_NE(ids.CodegenReadAfterWrite, ids.CodegenForNumericBackEdge);
}

// ---- PARALLEL_FOR registers without FATAL and updates every row --------
//
TEST_F(LuaSystemCodegenTest, ParallelIncRegistersAndUpdatesEveryRow) {
    using IRComponents::C_CodegenSysPos;

    constexpr int kCount = 256;
    std::vector<IREntity::EntityId> entities;
    entities.reserve(kCount);
    for (int i = 0; i < kCount; ++i) {
        entities.push_back(IREntity::createEntity(C_CodegenSysPos(static_cast<float>(i), 0.0f)));
    }

    const IRSystem::SystemId sys = IRScript::CodegenRegistry::createSystem_CodegenParallelInc();
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    for (int i = 0; i < kCount; ++i) {
        EXPECT_FLOAT_EQ(
            IREntity::getComponent<C_CodegenSysPos>(entities[i]).x_,
            static_cast<float>(i) + 1.0f
        );
        EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(entities[i]).y_, 2.0f);
    }
}

// ---- #1353: row-alias optimisation preserves copy semantics --------------
//
// `CodegenReadAfterWrite` reads `r.x` AFTER writing column x through
// `setField`. The optimised emitter must keep `local r = arch.C:at(i)` a
// by-value copy here (a row alias would observe the just-written x). With an
// initial (x=3, y=7): x is overwritten to 99, then y is set from the
// PRE-write x (3). An (incorrect) alias would yield y == 99.

TEST_F(LuaSystemCodegenTest, ReadAfterWriteKeepsCopySemantics) {
    using IRComponents::C_CodegenSysPos;

    const auto e = IREntity::createEntity(C_CodegenSysPos(3.0f, 7.0f));

    const IRSystem::SystemId sys = IRScript::CodegenRegistry::createSystem_CodegenReadAfterWrite();
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(e).x_, 99.0f);
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(e).y_, 3.0f);
}

// ---- #1353: FOR_NUMERIC back-edge keeps copy semantics for outer binding --
//
// `CodegenForNumericBackEdge` binds `local a = arch.C:at(i)` before a
// for_numeric loop that writes field x inside the body. The back-edge
// analysis passes `cWritten || bodyWrites` so a read in iteration N+1
// must not see the write from iteration N via an alias. With an initial
// x=1.0 and 3 iterations (j=0,1,2), copy semantics yield x=2.0 (each
// write reads the unchanged copy 1.0). An incorrect alias would
// accumulate: 1→2→3→4.

TEST_F(LuaSystemCodegenTest, ForNumericBackEdgeKeepsCopySemantics) {
    using IRComponents::C_CodegenSysPos;

    const auto e = IREntity::createEntity(C_CodegenSysPos(1.0f, 0.0f));

    const IRSystem::SystemId sys =
        IRScript::CodegenRegistry::createSystem_CodegenForNumericBackEdge();
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {sys});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    // Copy semantics: each of the 3 iterations reads the original a.x (1.0)
    // and writes 1.0 + 1.0 = 2.0. An alias would accumulate to 4.0.
    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CodegenSysPos>(e).x_, 2.0f);
}

} // namespace
