// T-106 regression coverage: the codegen path mirrors the EVAL path's
// shape on the cases that map cleanly between them — defaults, type
// inference, ECS round-trip, archetype move, removal. Cases that
// concern features unique to EVAL mode (IComponentDataLuaTyped's
// per-field column variant, runtime field-index API, modifier-field
// auto-registration) stay in lua_component_register_test.cpp; per the
// architect plan those are EVAL-only and excluded from CODEGEN by design.
//
// The fixture .lua used to generate the included header is the sibling
// `lua_component_codegen_fixtures.lua`; both are processed by
// `cmake/lua_codegen` at build time via the `irreden_lua_codegen()`
// helper wired in `test/CMakeLists.txt`.

#include <gtest/gtest.h>

#include <irreden/ir_entity.hpp>
#include <irreden/script/lua_script.hpp>

// Generated by cmake/lua_codegen from lua_component_codegen_fixtures.lua.
// Path is added to the include search list by irreden_lua_codegen().
#include "lua_component_codegen_fixtures.hpp"

#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <string>
#include <type_traits>

// MSVC names the POSIX pipe-spawn helpers with a leading underscore.
#ifdef _WIN32
#define ir_popen _popen
#define ir_pclose _pclose
#else
#define ir_popen popen
#define ir_pclose pclose
#endif

namespace {

// LuaScript first so its sol::state outlives sol::function-bearing
// columns held by EntityManager (mirrors lua_component_register_test).
class LuaComponentCodegenTest : public testing::Test {
  protected:
    LuaComponentCodegenTest()
        : m_lua{}
        , m_entity_manager{} {
        m_lua.bindLuaDrivenEcs();
        IRScript::CodegenRegistry::registerCodegenComponents(m_lua);
    }

    IRScript::LuaScript m_lua;
    IREntity::EntityManager m_entity_manager;
};

// ---- Type inference (compile-time + default value checks) ------------------

TEST_F(LuaComponentCodegenTest, IntegerDefaultsInferAsInt32) {
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenHp::current_), std::int32_t>);
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenHp::max_), std::int32_t>);
    IRComponents::C_CodegenHp hp;
    EXPECT_EQ(hp.current_, 100);
    EXPECT_EQ(hp.max_, 100);
}

TEST_F(LuaComponentCodegenTest, FloatDefaultsInferAsFloat) {
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenVel::x_), float>);
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenVel::y_), float>);
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenVel::z_), float>);
    IRComponents::C_CodegenVel v;
    EXPECT_FLOAT_EQ(v.x_, 1.5f);
    EXPECT_FLOAT_EQ(v.y_, 1.5f);
    EXPECT_FLOAT_EQ(v.z_, 1.5f);
}

TEST_F(LuaComponentCodegenTest, MixedDefaultsInferPerField) {
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenMixed::tag_), std::string>);
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenMixed::alive_), bool>);
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenMixed::count_), std::int32_t>);
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenMixed::weight_), float>);
    IRComponents::C_CodegenMixed m;
    EXPECT_EQ(m.tag_, "hello");
    EXPECT_TRUE(m.alive_);
    EXPECT_EQ(m.count_, 42);
    EXPECT_FLOAT_EQ(m.weight_, 3.5f);
}

TEST_F(LuaComponentCodegenTest, ExplicitTypeFormForcesFloatOverIntegerDefault) {
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenHpForced::current_), float>);
    IRComponents::C_CodegenHpForced f;
    EXPECT_FLOAT_EQ(f.current_, 100.0f);
}

// ---- Native storage & ECS round-trip ---------------------------------------

TEST_F(LuaComponentCodegenTest, AttachToHundredEntitiesUsesNativeStorage) {
    // CODEGEN structs flow through the standard IComponentDataImpl<T> path:
    // attaching N entities materialises one column of N C_CodegenHp values
    // (not the per-field variant of IComponentDataLuaTyped).
    constexpr int kCount = 100;
    for (int i = 0; i < kCount; ++i) {
        IREntity::EntityId e = IREntity::createEntity();
        m_entity_manager.setComponent(e, IRComponents::C_CodegenHp{});
    }
    int sampled = 0;
    IREntity::forEachComponent<IRComponents::C_CodegenHp>([&](const IRComponents::C_CodegenHp &hp) {
        EXPECT_EQ(hp.current_, 100);
        EXPECT_EQ(hp.max_, 100);
        ++sampled;
    });
    EXPECT_EQ(sampled, kCount);
}

TEST_F(LuaComponentCodegenTest, FieldOverridesWriteThroughToColumn) {
    IREntity::EntityId e = IREntity::createEntity();
    m_entity_manager.setComponent(e, IRComponents::C_CodegenHp{50, 75});
    auto &hp = IREntity::getComponent<IRComponents::C_CodegenHp>(e);
    EXPECT_EQ(hp.current_, 50);
    EXPECT_EQ(hp.max_, 75);
}

// ---- Archetype move correctness -------------------------------------------

struct ArchetypeMoveCodegenMarker {};

TEST_F(LuaComponentCodegenTest, ArchetypeMovePreservesFieldValues) {
    IREntity::EntityId e = IREntity::createEntity();
    m_entity_manager.setComponent(e, IRComponents::C_CodegenHp{50, 100});

    // Trigger an archetype move by adding an unrelated marker component.
    IREntity::setComponent(e, ArchetypeMoveCodegenMarker{});

    auto &hp = IREntity::getComponent<IRComponents::C_CodegenHp>(e);
    EXPECT_EQ(hp.current_, 50);
    EXPECT_EQ(hp.max_, 100);
}

// ---- Lua binding handle visibility -----------------------------------------

TEST_F(LuaComponentCodegenTest, RegisterCodegenComponentsExposesLuaHandle) {
    // After registerCodegenComponents(), the C++ component types are
    // recorded under their unprefixed Lua-visible names (`CodegenHp`,
    // not `C_CodegenHp`) to match the user-facing form in
    // `IRComponent.register('Hp', ...)`; the IRComponent.<name> handle
    // should resolve via the same machinery the EVAL path uses for
    // handwritten lua_component_pack types.
    auto &lua = m_lua.lua();
    auto result =
        lua.safe_script("return type(IRComponent.CodegenHp), IRComponent.CodegenHp.componentId");
    ASSERT_TRUE(result.valid());
    auto [handleType, componentId] = result.get<std::tuple<std::string, lua_Integer>>();
    EXPECT_EQ(handleType, "table");
    EXPECT_GT(componentId, 0);
}

// ---- Lua usertype field accessors ------------------------------------------

TEST_F(LuaComponentCodegenTest, LuaFieldAccessorReturnsValue) {
    // Codegen-emitted usertype is bound under the unprefixed name
    // (`CodegenHp`, not `C_CodegenHp`) and fields are member-pointer
    // properties (`hp.current`, not `hp:current()`). Both shifts support
    // EVAL bodies in coexistence mode reading and writing fields with
    // property syntax instead of getter-call syntax.
    auto &lua = m_lua.lua();
    auto result = lua.safe_script(
        "local hp = CodegenHp.new(7, 11)\n"
        "return hp.current, hp.max"
    );
    ASSERT_TRUE(result.valid());
    auto [current, max] = result.get<std::tuple<lua_Integer, lua_Integer>>();
    EXPECT_EQ(current, 7);
    EXPECT_EQ(max, 11);
}

// ---- Schema-error coverage (subprocess invocation) -------------------------

// #1403: CodegenDevice.kind defaults to CodegenDeviceType.SYNTH (0-based
// ordinal 1). Proves the codegen IREnum shim built the enum table and
// resolved the member during the capture pass, and that codegen and EVAL
// assign identical ordinals (both go through detail::buildLuaEnumTable).
TEST_F(LuaComponentCodegenTest, EnumMemberResolvesAsFieldDefaultDuringCodegen) {
    static_assert(std::is_same_v<decltype(IRComponents::C_CodegenDevice::kind_), std::int32_t>);
    IRComponents::C_CodegenDevice d;
    EXPECT_EQ(d.kind_, 1);
}

// Runs the codegen binary on a fixture that uses the explicit
// `{ type = 'int32', default = <out-of-range> }` form and verifies the tool
// errors out with a clear diagnostic instead of silently truncating. The
// short-form path's matching guard is exercised implicitly by the rest of
// this suite — the explicit-form path is the regression surface here
// (PR #596 review).
TEST(LuaComponentCodegenSchemaError, ExplicitInt32OverflowRaisesError) {
    const std::filesystem::path outPath =
        std::filesystem::temp_directory_path() / "ir_lua_codegen_overflow.hpp";
    std::filesystem::remove(outPath);

    const std::string cmd = std::string{IR_LUA_CODEGEN_BINARY} + " --out " + outPath.string() +
                            " " + IR_LUA_CODEGEN_OVERFLOW_FIXTURE + " 2>&1";

    FILE *pipe = ir_popen(cmd.c_str(), "r");
    ASSERT_NE(pipe, nullptr) << "failed to spawn ir_lua_codegen";

    std::string output;
    char buf[256];
    while (std::fgets(buf, sizeof(buf), pipe) != nullptr) {
        output += buf;
    }
    const int status = ir_pclose(pipe);

    EXPECT_NE(status, 0) << "codegen tool should fail on int32 overflow; output: " << output;
    EXPECT_NE(output.find("out of int32 range"), std::string::npos)
        << "expected 'out of int32 range' diagnostic; got: " << output;
    EXPECT_FALSE(std::filesystem::exists(outPath))
        << "codegen tool should not write output on schema error";
}

// #1403: the codegen IREnum shim validates member lists at build time. A
// non-string member must abort the tool with the same diagnostic the EVAL
// path raises (shared detail::buildLuaEnumTable), and no header is written.
TEST(LuaEnumCodegenSchemaError, NonStringMemberRaisesError) {
    const std::filesystem::path outPath =
        std::filesystem::temp_directory_path() / "ir_lua_codegen_enum_error.hpp";
    std::filesystem::remove(outPath);

    const std::string cmd = std::string{IR_LUA_CODEGEN_BINARY} + " --out " + outPath.string() +
                            " " + IR_LUA_CODEGEN_ENUM_ERROR_FIXTURE + " 2>&1";

    FILE *pipe = ir_popen(cmd.c_str(), "r");
    ASSERT_NE(pipe, nullptr) << "failed to spawn ir_lua_codegen";

    std::string output;
    char buf[256];
    while (std::fgets(buf, sizeof(buf), pipe) != nullptr) {
        output += buf;
    }
    const int status = ir_pclose(pipe);

    EXPECT_NE(status, 0) << "codegen tool should fail on non-string enum member; output: "
                         << output;
    EXPECT_NE(output.find("is not a string"), std::string::npos)
        << "expected 'is not a string' diagnostic; got: " << output;
    EXPECT_FALSE(std::filesystem::exists(outPath))
        << "codegen tool should not write output on schema error";
}

} // namespace
