// A second translation unit including the SAME codegen run's generated header
// as `lua_component_codegen_test.cpp` — the regression lock for #3091.
//
// This file's job is to LINK. A generated header that defines (rather than
// declares) its `IRScript::CodegenClaims::C_<Name>_declared_by_…` constants
// makes a second includer a duplicate-symbol error under a symbol name naming
// the wrong cause, so `IrredenEngineTest` failing to link here is the signal
// that the definitions drifted back out of the companion `_claims.cpp`.
//
// The value-level accessors exist so the test TU can check that both TUs see
// one type, not two structurally identical ones.

#include "lua_component_codegen_second_tu.hpp"

// Generated by cmake/lua_codegen from lua_component_codegen_fixtures.lua; the
// include path is added by irreden_lua_codegen(). This is the second includer.
#include "lua_component_codegen_fixtures.hpp"

namespace IRTestCodegenSecondTu {

const std::type_info &hpTypeId() {
    return typeid(IRComponents::C_CodegenHp);
}

void makeHp(int current, int max, int &outCurrent, int &outMax) {
    const IRComponents::C_CodegenHp hp{current, max};
    outCurrent = hp.current_;
    outMax = hp.max_;
}

std::size_t hpSize() {
    return sizeof(IRComponents::C_CodegenHp);
}

} // namespace IRTestCodegenSecondTu
