// T-108 regression coverage: the per-system `mode` override + CODEGEN/EVAL
// coexistence path. One Lua fixture file declares two systems that touch
// the same Lua-defined component — one CODEGEN (no mode field, follows
// the build-time --default-mode=codegen) and one EVAL (explicit mode =
// "eval"). The test asserts:
//
//  - Both systems register at startup. The CODEGEN one comes back as a
//    field on `CodegenSystemIds` returned by `registerCodegenSystems()`;
//    the EVAL one's SystemId is captured in a Lua global by the fixture
//    file's `IRSystem.registerSystem({mode='eval', ...})` call after the
//    file is loaded at runtime.
//
//  - Both systems tick correctly in the same pipeline. State changes from
//    one are visible to the other on the next tick (they share the same
//    `IRComponents::C_CoexistPos` archetype column).
//
//  - The EVAL one's body is hot-reloadable via
//    `IRSystem.replaceSystemBody`; the CODEGEN one's is NOT — attempting
//    to hot-reload it raises a Lua error pointing at the mode requirement.
//
//  - `IRComponent.register` is idempotent for components that the codegen
//    pipeline already pre-registered as C++ structs (otherwise the
//    runtime .lua load would conflict with `registerCodegenComponents`).

#include <gtest/gtest.h>

#include <irreden/ir_entity.hpp>
#include <irreden/ir_system.hpp>
#include <irreden/ir_time.hpp>
#include <irreden/script/lua_script.hpp>

#include <string>

// Generated by cmake/lua_codegen from lua_system_coexistence_fixtures.lua.
// Path is added to the include search list by irreden_lua_codegen().
#include "lua_system_coexistence_fixtures.hpp"

namespace {

class LuaSystemCoexistenceTest : public testing::Test {
  protected:
    LuaSystemCoexistenceTest()
        : m_lua{}
        , m_entity_manager{}
        , m_system_manager{} {
        m_lua.bindLuaDrivenEcs();
        IRScript::CodegenRegistry::registerCodegenComponents(m_lua);
        // Mirror the build-time default (CODEGEN by default for this fixture)
        // so the runtime pass over the same .lua file no-ops the unmarked
        // IRSystem.registerSystem call instead of double-registering it.
        m_lua.setEcsDefaultMode(IRScript::CodegenRegistry::kDefaultEcsMode);
    }

    // Path to the .lua fixture relative to the test binary's working dir.
    // The fixture lives next to the test source; the build copies it into
    // the binary tree via the `copy_all_lua_files` target wired in
    // creations/template/CMakeLists.txt-equivalent (see test/CMakeLists.txt).
    std::string fixturePath() const {
        return std::string{IR_LUA_COEXIST_FIXTURE_PATH};
    }

    IRScript::LuaScript m_lua;
    IREntity::EntityManager m_entity_manager;
    IRSystem::SystemManager m_system_manager;
};

TEST_F(LuaSystemCoexistenceTest, BothModesRegisterAndTickInOnePipeline) {
    using IRComponents::C_CoexistPos;

    // Pre-create the entity so the archetype exists before either system
    // is registered. Mirrors what a real creation would do (entity init →
    // pipeline init).
    const auto entity = IREntity::createEntity(C_CoexistPos(0.0f));

    // CODEGEN system via the codegen-emitted helper. Returns the SystemId
    // for the typed `IRSystem::createSystem<C_CoexistPos>` specialisation.
    const auto ids = IRScript::CodegenRegistry::registerCodegenSystems();
    const IRSystem::SystemId codegenSysId = ids.CoexistAddOneCodegen;
    EXPECT_LT(codegenSysId, m_system_manager.getSystemCount());
    EXPECT_STREQ(m_system_manager.getSystemName(codegenSysId).c_str(), "CoexistAddOneCodegen");

    // EVAL system via the runtime Lua path. The .lua fixture's
    // `IRSystem.registerSystem({mode='eval', ...})` returns a SystemId; the
    // fixture parks it in a Lua global so we can fetch it from C++.
    m_lua.scriptFile(fixturePath().c_str());
    const sol::object evalIdObj = m_lua.lua()["CoexistEvalSysId"];
    ASSERT_TRUE(evalIdObj.is<lua_Integer>())
        << "Fixture did not park CoexistEvalSysId as an integer global "
           "(EVAL registration may have no-oped)";
    const auto evalSysId = static_cast<IRSystem::SystemId>(evalIdObj.as<lua_Integer>());
    EXPECT_NE(evalSysId, IRSystem::SystemId{0})
        << "EVAL registration returned 0 — runtime mode dispatch is treating "
           "mode='eval' as CODEGEN";
    EXPECT_LT(evalSysId, m_system_manager.getSystemCount());
    EXPECT_NE(evalSysId, codegenSysId);

    // Pipeline: CODEGEN runs first (+1), then EVAL (+10). Net +11 per tick.
    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {codegenSysId, evalSysId});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CoexistPos>(entity).x_, 11.0f)
        << "Both systems should have ticked the same archetype column";
}

TEST_F(LuaSystemCoexistenceTest, EvalSystemBodyIsHotReloadable) {
    using IRComponents::C_CoexistPos;
    const auto entity = IREntity::createEntity(C_CoexistPos(0.0f));

    const auto ids = IRScript::CodegenRegistry::registerCodegenSystems();
    m_lua.scriptFile(fixturePath().c_str());
    const auto evalSysId =
        static_cast<IRSystem::SystemId>(m_lua.lua()["CoexistEvalSysId"].get<lua_Integer>());

    // Replace the EVAL body with one that adds 100 instead of 10.
    sol::protected_function_result hotReload = m_lua.lua().safe_script(
        "IRSystem.replaceSystemBody(CoexistEvalSysId, function(arch)\n"
        "    for i = 0, arch.length - 1 do\n"
        "        local p = arch.CoexistPos:at(i)\n"
        "        arch.CoexistPos:setAt(i, CoexistPos.new(p.x + 100.0))\n"
        "    end\n"
        "end)\n",
        sol::script_pass_on_error
    );
    ASSERT_TRUE(hotReload.valid())
        << "replaceSystemBody on the EVAL system raised an error: " << sol::error{hotReload}.what();

    m_system_manager.registerPipeline(IRTime::Events::UPDATE, {evalSysId});
    m_system_manager.executePipeline(IRTime::Events::UPDATE);

    EXPECT_FLOAT_EQ(IREntity::getComponent<C_CoexistPos>(entity).x_, 100.0f)
        << "Hot-reloaded EVAL body did not take effect";
    (void)ids;
}

TEST_F(LuaSystemCoexistenceTest, CodegenSystemBodyIsNotHotReloadable) {
    const auto ids = IRScript::CodegenRegistry::registerCodegenSystems();
    m_lua.scriptFile(fixturePath().c_str());

    // Attempting to hot-reload the CODEGEN system's body must surface a
    // clear Lua error pointing at the mode requirement (the architect plan
    // specifies the message must mention CODEGEN and the eval-mode escape
    // hatch). The CODEGEN SystemId is in SystemManager but absent from
    // m_luaSystemTicks, so the runtime path fires the T-108 error string.
    const std::string script = "IRSystem.replaceSystemBody(" +
                               std::to_string(ids.CoexistAddOneCodegen) + ", function() end)";
    sol::protected_function_result reload =
        m_lua.lua().safe_script(script, sol::script_pass_on_error);
    ASSERT_FALSE(
        reload.valid()
    ) << "replaceSystemBody on the CODEGEN system unexpectedly succeeded";

    const std::string err = sol::error{reload}.what();
    EXPECT_NE(err.find("hot-reload not supported"), std::string::npos) << err;
    EXPECT_NE(err.find("CODEGEN"), std::string::npos) << err;
    EXPECT_NE(err.find("mode='eval'"), std::string::npos) << err;
}

TEST_F(LuaSystemCoexistenceTest, ComponentRegisterIsIdempotentInCoexistenceMode) {
    // The .lua fixture calls `IRComponent.register('CoexistPos', {...})`
    // even though the same component was already pre-registered as a C++
    // codegen'd struct. Without the idempotency carve-out, the runtime
    // load would create a parallel `IComponentDataLuaTyped` under the
    // same Lua name, splitting archetype storage. The script should
    // execute cleanly and the second registration should reuse the
    // existing handle.
    sol::protected_function_result result =
        m_lua.lua().safe_script_file(fixturePath(), sol::script_pass_on_error);
    ASSERT_TRUE(result.valid()) << sol::error{result}.what();

    // The Lua-side handle must be the C++-bound one (carried in
    // IRComponent[name]), so the componentId field matches what the
    // codegen-side registration produced.
    const sol::table coexistPosHandle = m_lua.lua()["IRComponent"]["CoexistPos"];
    ASSERT_TRUE(coexistPosHandle.valid());
    const auto handleId =
        static_cast<IREntity::ComponentId>(coexistPosHandle.get<lua_Integer>("componentId"));
    EXPECT_EQ(handleId, IREntity::getComponentType<IRComponents::C_CoexistPos>());
}

} // namespace
