"""Generate explicit command permissions for a dedicated Codex worktree."""

import json
import subprocess
from pathlib import Path

HEADER = "# Generated by fleet-codex; put personal rules in a different .rules file.\n"
GIT_READ = ("status", "diff", "log", "show", "rev-parse", "ls-files", "ls-tree", "rev-list")
GIT_WRITE = ("add", "commit", "push", "fetch", "checkout", "switch", "branch", "restore", "rebase")
REVIEW_ROLES = ("sonnet-reviewer", "opus-reviewer", "smoke-worker")


def rules(worktree, role):
    lines = [HEADER.rstrip()]

    def rule(pattern, decision):
        lines.append(f"prefix_rule(pattern={json.dumps(pattern)}, decision={json.dumps(decision)})")

    # Ordinary interpreters/test runners execute inside the sandbox, never via
    # an unrestricted prefix exception. Git -C exceptions name this checkout.
    for prefix in (["git"], ["git", "-C", str(worktree)]):
        rule(prefix + [list(GIT_READ)], "allow")
        rule(prefix + [list(GIT_WRITE)], "allow")
        for verb in ("reset", "clean"):
            rule(prefix + [verb], "forbidden")
        for flag in ("--force", "-f", "--force-with-lease", "--delete"):
            rule(prefix + ["push", flag], "forbidden")
            rule(prefix + ["push", "origin", flag], "forbidden")
        for ref in ("master", "main", "HEAD:master", "HEAD:main", ":master", ":main"):
            rule(prefix + ["push", "origin", ref], "forbidden")
        if role in REVIEW_ROLES:
            rule(prefix + [["commit", "push"]], "forbidden")
    rule(["gh", "pr", ["list", "view", "diff", "checks", "edit", "review"]], "allow")
    rule(["gh", "issue", ["list", "view", "edit", "comment"]], "allow")
    rule(["gh", "pr", "merge"], "forbidden")
    rule(["gh", "pr", "create"], "forbidden" if role in REVIEW_ROLES else "allow")
    rule(["gh", "auth", "status"], "allow")
    # Fleet wrappers enforce their own assignment scope and network timeouts.
    settings_path = Path(__file__).resolve().parents[2] / ".claude/settings.json"
    settings = json.loads(settings_path.read_text())
    excluded = {"fleet-up", "fleet-down", "fleet-dispatcher", "fleet-babysit", "fleet-rebase",
                "fleet-dispatch-wrap", "fleet-state-scout", "fleet-claude-stream", "fleet-runtime"}
    for entry in settings.get("permissions", {}).get("allow", []):
        if entry.startswith("Bash(fleet-") and entry.endswith(":*)"):
            name = entry[5:-3]
            if name not in excluded:
                rule([name], "allow")
    if role in REVIEW_ROLES:
        rule(["fleet-pr-amend-push"], "forbidden")
    rule(["fleet-runtime", "stamp"], "forbidden" if role in REVIEW_ROLES else "allow")
    for name in ("sudo",):
        rule([name], "forbidden")
    return "\n".join(lines) + "\n"


def _is_fleet_generated(text):
    # Structural check, not byte-equality against a fresh regeneration: a
    # settings.json/rules() change must not read as hand-authored.
    lines = text.splitlines()
    if not lines or lines[0] != HEADER.rstrip():
        return False
    return all(line.startswith("prefix_rule(") for line in lines[1:] if line)


def prepare(worktree, role):
    path = worktree / ".codex/rules/fleet.rules"
    if path.is_symlink():
        raise ValueError("refusing to overwrite a symlinked fleet policy")
    if path.exists() and not _is_fleet_generated(path.read_text()):
        raise ValueError(f"hand-authored policy at {path}; move it before preparing")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rules(worktree, role))
    return path


def check(path, role):
    cases = [(["git", "status"], "allow"), (["gh", "pr", "list"], "allow"),
             (["gh", "pr", "merge", "123"], "forbidden"),
             (["git", "push", "origin", "master"], "forbidden"),
             (["git", "push", "--force", "origin", "HEAD"], "forbidden"),
             (["git", "commit", "-m", "test"],
              "forbidden" if role in REVIEW_ROLES else "allow")]
    for cmd, expected in cases:
        result = subprocess.run(["codex", "execpolicy", "check", "--rules", str(path), "--", *cmd],
                                check=True, capture_output=True, text=True, timeout=15)
        actual = json.loads(result.stdout).get("decision")
        if actual != expected:
            raise ValueError(f"policy mismatch for {cmd}: expected {expected}, got {actual}")
    return len(cases)
