#!/usr/bin/env python3
"""Ratchet: issue and PR numbers do not belong in code comments.

The rule lives in `.claude/rules/comments.md`: a comment explains what the code
cannot say for itself, never where the code came from. A bare issue number in
a comment is a pointer into a tracker the source tree does not own, and it
rots the day the issue closes. History belongs in commit messages, PR bodies,
and `docs/design/`.

The tree carried thousands of these when the rule landed, so this is a
ratchet, not a ban switch: `lint_comment_refs_baseline.json` records the count
per file at the time each file was last swept, the lint fails only when a
file exceeds its recorded count, and `--update-baseline` may lower a count or
drop a file but never raise one. A file absent from the baseline has a budget
of zero. CI checks a pull request against the base branch's baseline, so a
baseline edit in the same PR cannot buy budget; a reviewer rejects any
baseline diff that raises a count. The baseline is regenerated by hand only
when the parser or its population changes (`write_baseline(scan_tree()[0])`
from a Python prompt), in the same PR, where the newly counted files are
visible in the diff.

Population: git-tracked C, C++, Objective-C++, shader, Lua, Python, shell,
PowerShell, Starlark, and CMake sources, plus every tracked extension-less
file whose first line names an interpreter. Vendored and generated trees are
skipped.

Comments are found by a tokenizer per comment syntax, never one shared across
languages: what is *not* a comment is what differs between them. Each steps
over that language's string literals, character literals, raw strings, and
block comments, so a ticket-shaped value in a string is never a hit — and the
shell and CMake tokenizers additionally step over here-documents and bracket
arguments, whose `#` opens nothing. What an interpreter reads as source is the
exception: a here-document that feeds one or whose body opens with a shebang,
and a `-c` program string in any of its quotings, are scanned as that
language. Whether an interpreter reads it is decided by the command word of
the simple command — reached through assignments, keywords, and prefixes such
as `env`, `sudo` and `timeout` together with their option operands — so
`sudo -u root python3 -c '…'` is source while `echo python3 -c '…'` is data.

Exit 0: no file exceeds its budget. Exit 1: at least one does, printed as
`file:line: <comment>`; the summary names the baseline command to run after a
genuine sweep.
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BASELINE = Path(__file__).resolve().with_name("lint_comment_refs_baseline.json")

SLASH_COMMENT_EXTS = {".hpp", ".cpp", ".h", ".hh", ".hxx", ".cc", ".cxx", ".c",
                      ".tpp", ".inl", ".mm", ".m", ".glsl", ".metal"}
# Starlark is Python's syntax, down to the triple-quoted string.
PYTHON_EXTS = {".py", ".bzl", ".bazel"}
SHELL_COMMENT_EXTS = {".sh", ".bash", ".zsh"}
POWERSHELL_COMMENT_EXTS = {".ps1"}
CMAKE_COMMENT_EXTS = {".cmake"}
CMAKE_COMMENT_NAMES = {"CMakeLists.txt"}
DASH_COMMENT_EXTS = {".lua"}
SKIP_PREFIXES = (
    "engine/render/third_party/",
    "engine/render/include/irreden/render/gl_wrap/",
    "third_party/",
    "build/",
    # The checker and its fixtures spell the pattern they detect.
    "scripts/lint_comment_refs.py",
    "scripts/fleet/tests/test_lint_comment_refs.py",
)
INTERPRETER_RE = re.compile(r"^#!.*\b(python\d*|bash|sh|zsh)\b")
# Three digits is a floor against ordinals, not a tracker range: `Rule #5`,
# `invariant #1` and `acceptance criterion #3` are shapes the tree uses
# freely. There is no ceiling — the tracker outgrows four digits.
REF_RE = re.compile(r"#\d{3,}\b")
RAW_STRING_RE = re.compile(r'(?:u8|u|U|L)?R"([^\s()\\]{0,16})\(')


def tracked_files():
    out = subprocess.run(["git", "-C", str(REPO), "ls-files", "-z"],
                         capture_output=True, text=True, check=True).stdout
    return [p for p in out.split("\0") if p]


def comment_family(rel):
    """`slash`, `python`, `shell`, `cmake`, `powershell`, or `dash` for a file
    the ratchet covers, else None. Each family is one comment syntax: families
    do not share a tokenizer, because what is not a comment differs between
    them (a shell here-document, a CMake bracket argument, a PowerShell
    here-string all carry `#` that starts nothing)."""
    if rel.startswith(SKIP_PREFIXES):
        return None
    p = Path(rel)
    if p.suffix in SLASH_COMMENT_EXTS:
        return "slash"
    if p.suffix in PYTHON_EXTS:
        return "python"
    if p.suffix in SHELL_COMMENT_EXTS:
        return "shell"
    if p.suffix in POWERSHELL_COMMENT_EXTS:
        return "powershell"
    if p.suffix in CMAKE_COMMENT_EXTS or p.name in CMAKE_COMMENT_NAMES:
        return "cmake"
    if p.suffix in DASH_COMMENT_EXTS:
        return "dash"
    if p.suffix == "" and not p.name.startswith("."):
        try:
            with open(REPO / rel, errors="replace") as f:
                first = f.readline()
        except OSError:
            return None
        return _shebang_family(first)
    return None


def _skip_quoted(text, i, quote, escape="\\", multiline=False):
    """Index just past the string that opens at text[i] (a `quote` char).
    `escape` is the literal that quotes the next character, or None where the
    syntax has none. A single-line string that is never closed ends at the
    newline; a multi-line one runs to end of input."""
    i += 1
    n = len(text)
    while i < n:
        ch = text[i]
        if escape and ch == escape and i + 1 < n and text[i + 1] != "\n":
            i += 2
            continue
        if ch == quote:
            return i + 1
        if ch == "\n" and not multiline:
            return i
        i += 1
    return n


def _skip_to(text, i, terminator):
    """Index just past `terminator`; end of input when it never appears. For
    constructs that swallow the rest of the file when unclosed — a block
    comment, a raw string."""
    end = text.find(terminator, i)
    return len(text) if end < 0 else end + len(terminator)


def _find_close(text, i, terminator):
    """Index just past `terminator`, or None when it never appears. For
    constructs a missing terminator disqualifies rather than extends: an
    unclosed here-document or bracket argument means the opener was never one,
    and running to end of input would blank away real comments."""
    end = text.find(terminator, i)
    return None if end < 0 else end + len(terminator)


def _mask_slash(text):
    """C-family: `//` to end of line, `/* ... */` blocks; steps over string,
    character, and raw-string literals."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        two = text[i:i + 2]
        if two == "//":
            end = text.find("\n", i)
            end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif two == "/*":
            end = _skip_to(text, i, "*/")
            out.append(text[i:end])
            i = end
        elif ch in "RuUL" and (i == 0 or not _ident(text[i - 1])) \
                and RAW_STRING_RE.match(text, i):
            m = RAW_STRING_RE.match(text, i)
            end = _skip_to(text, m.end(), ")" + m.group(1) + '"')
            out.append(_blank(text[i:end]))
            i = end
        elif ch == '"':
            end = _skip_quoted(text, i, '"')
            out.append(_blank(text[i:end]))
            i = end
        elif ch == "'":
            end = _skip_quoted(text, i, "'")
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


def _mask_python(text):
    """Python and Starlark: `#` to end of line; steps over quoted and
    triple-quoted strings."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        if ch == "#":
            end = text.find("\n", i)
            end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif text[i:i + 3] in ('"""', "'''"):
            end = _skip_to(text, i + 3, text[i:i + 3])
            out.append(_blank(text[i:end]))
            i = end
        elif ch in "\"'":
            end = _skip_quoted(text, i, ch)
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


# `<<` or `<<-` then the delimiter word, bare or quoted. A bare delimiter must
# open like an identifier so that an arithmetic left shift is not read as a
# here-document.
HEREDOC_RE = re.compile(
    r"""<<(-?)[ \t]*(?:'([^'\n]*)'|"([^"\n]*)"|\\?([A-Za-z_][A-Za-z0-9_]*))""")
SHELL_WORD_BREAK = " \t\n;&|()<>"
EMBEDDED_INTERPRETER_RE = re.compile(r"\b(python\d*|bash|sh|zsh)\b")
# The `$` is bash and zsh quoting — `$'...'` takes escapes, `$"..."` is
# locale-translated — and neither ends the `-c` argument it opens.
DASH_C_RE = re.compile(r"(?:^|[\s;&|(])-c[ \t]*\$?$")


def _interpreter_family(name):
    return "python" if name.startswith("python") else "shell"


SHELL_COMMAND_PREFIXES = {"command", "builtin", "exec", "env", "nohup", "sudo",
                          "nice", "time", "timeout", "xargs", "caffeinate"}
SHELL_KEYWORDS = {"if", "then", "else", "elif", "fi", "do", "done", "while",
                  "until", "!", "{", "}"}
SHELL_ASSIGNMENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")
SHELL_NUMBER_RE = re.compile(r"^\d+[smhd]?$")
COMMAND_SEPARATOR_RE = re.compile(r"[;|&]+|\$\(|[(){}`]")
# Options of the supported prefixes that take a *separate* operand, so the
# word after one is that option's value and not yet the command word. The
# `--opt=value` spelling carries its own operand and needs no entry. A prefix
# absent here has no operand-bearing option worth honouring; listing one too
# few misses an invocation, listing one too many reads a command word as data.
PREFIX_OPTION_OPERANDS = {
    "env": {"-u", "--unset", "-C", "--chdir", "-S", "--split-string"},
    "exec": {"-a"},
    "nice": {"-n", "--adjustment"},
    "sudo": {"-u", "--user", "-g", "--group", "-p", "--prompt", "-C",
             "--close-from", "-D", "--chdir", "-R", "--chroot", "-h", "--host",
             "-T", "--command-timeout", "-U", "--other-user", "-r", "--role",
             "-t", "--type"},
    "time": {"-f", "--format", "-o", "--output"},
    "timeout": {"-s", "--signal", "-k", "--kill-after"},
    "xargs": {"-I", "--replace", "-L", "--max-lines", "-n", "--max-args",
              "-P", "--max-procs", "-s", "--max-chars", "-d", "--delimiter",
              "-E", "--eof", "-a", "--arg-file"},
    "caffeinate": {"-t", "-w"},
}


def _shell_words(segment):
    """The segment's words, with quoted runs kept whole. A plain `split()`
    breaks `FOO="x y"` at the space inside the value, which puts the command
    word on the tail of an assignment instead of the command that follows it.
    A backslash-newline is the line continuation the shell deletes."""
    words, word, i, n = [], None, 0, len(segment)
    while i < n:
        ch = segment[i]
        if ch in " \t\n":
            if word is not None:
                words.append(word)
                word = None
            i += 1
        elif ch == "\\" and segment[i + 1:i + 2] == "\n":
            i += 2
        elif ch == "\\" and i + 1 < n:
            word = (word or "") + segment[i:i + 2]
            i += 2
        elif ch in "\"'":
            # `$'...'` is the one single-quoted form that takes escapes.
            escape = "\\" if ch == '"' or segment[i - 1:i] == "$" else None
            end = _skip_quoted(segment, i, ch, escape, multiline=True)
            word = (word or "") + segment[i:end]
            i = end
        else:
            word = (word or "") + ch
            i += 1
    if word is not None:
        words.append(word)
    return words


def _last_separator_end(segment):
    """The offset just past the segment's last command separator, counting only
    separators the shell would act on. A separator is inert inside a quoted run
    or behind a backslash, so `FOO="x; y" python3 -c …` is one simple command
    whose command word is the interpreter; reading that `;` as a boundary puts
    the command word out of reach. Quoting is honoured exactly as
    `_shell_words` honours it, so the two agree on where a word begins."""
    cut, i, n = 0, 0, len(segment)
    while i < n:
        ch = segment[i]
        if ch == "\\" and i + 1 < n:
            i += 2
            continue
        if ch in "\"'":
            escape = "\\" if ch == '"' or segment[i - 1:i] == "$" else None
            i = _skip_quoted(segment, i, ch, escape, multiline=True)
            continue
        m = COMMAND_SEPARATOR_RE.match(segment, i)
        if m:
            cut = i = m.end()
            continue
        i += 1
    return cut


def _command_family(text, i):
    """The family of the interpreter that is the command word of the simple
    command containing position `i`, else None: `python3 <<'PY'` and
    `sudo -u root python3 -c '...'` feed Python source; `echo python3 -c '...'`
    and `cat <<'EOF'` feed data. The command word is the first word of the
    segment after the last separator on the logical line, skipping
    assignments, shell keywords, and the common command-prefix forms —
    including, for a prefix that takes one, an option's separate operand,
    which is otherwise mistaken for the command word (`sudo -u root …`).
    Both the separator search and the word split honour quoting, so neither a
    quoted assignment value nor a separator character inside one stands in for
    the command word (`FOO="x; y" python3 -c …`)."""
    start = text.rfind("\n", 0, i) + 1
    while start > 1 and text[start - 2] == "\\":
        start = text.rfind("\n", 0, start - 1) + 1
    segment = text[start:i]
    cut = _last_separator_end(segment)
    operand_options = frozenset()
    skip_operand = False
    for word in _shell_words(segment[cut:]):
        if skip_operand:
            skip_operand = False
            continue
        name = word.rsplit("/", 1)[-1]
        if name in SHELL_COMMAND_PREFIXES:
            operand_options = PREFIX_OPTION_OPERANDS.get(name, frozenset())
            continue
        if word.startswith("-"):
            skip_operand = word in operand_options
            continue
        if (word in SHELL_KEYWORDS or SHELL_ASSIGNMENT_RE.match(word)
                or SHELL_NUMBER_RE.match(word)):
            continue
        return _interpreter_family(name) if EMBEDDED_INTERPRETER_RE.fullmatch(name) else None
    return None


def _shebang_family(body):
    """The family a here-document body declares for itself, as a script written
    out to a file does. Same signal the population uses on an extension-less
    file."""
    m = INTERPRETER_RE.match(body.split("\n", 1)[0])
    return _interpreter_family(m.group(1)) if m else None


def _program_string_family(text, i):
    """The family of a quoted string that is an interpreter's `-c` program
    argument, else None. `python3 -c '...'` holds Python source, so its `#`
    lines are comments; every other quoted string is a value. A `$` prefix
    and an absent space are both spellings of the same argument."""
    start = text.rfind("\n", 0, i) + 1
    if not DASH_C_RE.search(text, start, i):
        return None
    return _command_family(text, i)


def _mask_embedded(body, family):
    """A here-document body is data to the shell, but when the document feeds
    an interpreter the body is that language's source and its comments are
    comments — the rule reaches them too."""
    if family == "python":
        return _mask_python(body)
    if family == "shell":
        return _mask_shell(body)
    return _blank(body)


def _heredoc_end(text, i, delim, strip_tabs):
    """Index just past the here-document terminator line, scanning from the
    start of a line at `i`; None when the body is never terminated."""
    n = len(text)
    while i <= n:
        nl = text.find("\n", i)
        line = text[i:] if nl < 0 else text[i:nl]
        if (line.lstrip("\t") if strip_tabs else line) == delim:
            return n if nl < 0 else nl + 1
        if nl < 0:
            return None
        i = nl + 1
    return None


def _mask_shell(text):
    """POSIX shell, bash, zsh: `#` starts a comment only at a word start, and
    runs to end of line. Steps over backslash escapes, single- and
    double-quoted strings (both of which span lines), and here-document
    bodies, none of which are comments however many `#` they carry — except
    that a document feeding an interpreter is scanned as that language."""
    out, i, n = [], 0, len(text)
    pending = []
    while i < n:
        ch = text[i]
        if ch == "\n":
            out.append("\n")
            i += 1
            while pending:
                delim, strip_tabs, embedded = pending.pop(0)
                end = _heredoc_end(text, i, delim, strip_tabs)
                if end is None:
                    break
                body = text[i:end]
                out.append(_mask_embedded(body, embedded or _shebang_family(body)))
                i = end
        elif ch == "\\" and i + 1 < n:
            out.append(_blank(text[i:i + 2]))
            i += 2
        elif ch == "#" and (i == 0 or text[i - 1] in SHELL_WORD_BREAK):
            end = text.find("\n", i)
            end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif ch == "<" and HEREDOC_RE.match(text, i):
            m = HEREDOC_RE.match(text, i)
            pending.append((m.group(2) or m.group(3) or m.group(4),
                            m.group(1) == "-", _command_family(text, i)))
            out.append(_blank(m.group(0)))
            i = m.end()
        elif ch in "\"'":
            # `$'...'` is the one single-quoted form that takes escapes.
            escape = "\\" if ch == '"' or text[i - 1:i] == "$" else None
            end = _skip_quoted(text, i, ch, escape, multiline=True)
            program = _program_string_family(text, i)
            if program and end - 1 > i:
                out.append(" " + _mask_embedded(text[i + 1:end - 1], program) + " ")
            else:
                out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" ")
            i += 1
    return "".join(out)


BRACKET_OPEN_RE = re.compile(r"\[(=*)\[")


def _mask_cmake(text):
    """CMake: `#` to end of line and `#[=*[ ... ]=*]` bracket comments are
    comments; `[=*[ ... ]=*]` bracket arguments and quoted arguments, both of
    which span lines, are not."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        if ch == "#":
            m = BRACKET_OPEN_RE.match(text, i + 1)
            end = _find_close(text, m.end(), "]" + m.group(1) + "]") if m else None
            if end is None:
                end = text.find("\n", i)
                end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif ch == "[" and BRACKET_OPEN_RE.match(text, i):
            m = BRACKET_OPEN_RE.match(text, i)
            end = _find_close(text, m.end(), "]" + m.group(1) + "]")
            if end is None:
                out.append(" ")
                i += 1
                continue
            out.append(_blank(text[i:end]))
            i = end
        elif ch == '"':
            end = _skip_quoted(text, i, '"', multiline=True)
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


def _mask_powershell(text):
    """PowerShell: `#` to end of line and `<# ... #>` blocks are comments;
    here-strings (`@" ... "@`, `@' ... '@`) and quoted strings, all of which
    span lines, are not."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        two = text[i:i + 2]
        if two == "<#":
            end = _skip_to(text, i + 2, "#>")
            out.append(text[i:end])
            i = end
        elif ch == "#":
            end = text.find("\n", i)
            end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif two in ('@"', "@'"):
            end = _find_close(text, i + 2, "\n" + two[1] + "@")
            if end is None:
                out.append(" ")
                i += 1
                continue
            out.append(_blank(text[i:end]))
            i = end
        elif ch in "\"'":
            # A backtick, not a backslash, is PowerShell's escape.
            end = _skip_quoted(text, i, ch, "`" if ch == '"' else None,
                               multiline=True)
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


def _mask_dash(text):
    """Lua: `--` to end of line, `--[=*[ ... ]=*]` blocks; steps over quoted
    strings and `[=*[ ... ]=*]` long strings."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        if text[i:i + 2] == "--":
            m = BRACKET_OPEN_RE.match(text, i + 2)
            if m:
                end = _skip_to(text, m.end(), "]" + m.group(1) + "]")
            else:
                end = text.find("\n", i)
                end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif ch == "[" and BRACKET_OPEN_RE.match(text, i):
            m = BRACKET_OPEN_RE.match(text, i)
            end = _skip_to(text, m.end(), "]" + m.group(1) + "]")
            out.append(_blank(text[i:end]))
            i = end
        elif ch in ('"', "'"):
            end = _skip_quoted(text, i, ch)
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


def _blank(s):
    return "".join("\n" if c == "\n" else " " for c in s)


def _ident(c):
    return c.isalnum() or c == "_"


def comment_mask(text, family):
    """`text` with every non-comment character replaced by a space; line
    structure is preserved so line numbers survive."""
    if family == "slash":
        return _mask_slash(text)
    if family == "python":
        return _mask_python(text)
    if family == "shell":
        return _mask_shell(text)
    if family == "cmake":
        return _mask_cmake(text)
    if family == "powershell":
        return _mask_powershell(text)
    if family == "dash":
        return _mask_dash(text)
    raise ValueError(family)


def scan_text(text, family):
    """Lines whose comment portion carries an issue/PR reference, as
    `(line_no, stripped_line)`."""
    hits = []
    masked = comment_mask(text, family).split("\n")
    for n, (line, comment) in enumerate(zip(text.split("\n"), masked), 1):
        if REF_RE.search(comment):
            hits.append((n, line.strip()))
    return hits


def scan_file(rel, family):
    try:
        text = (REPO / rel).read_text(errors="replace")
    except OSError:
        return []
    return scan_text(text, family)


def scan_tree():
    counts, details = {}, {}
    for rel in tracked_files():
        family = comment_family(rel)
        if family is None:
            continue
        hits = scan_file(rel, family)
        if hits:
            counts[rel] = len(hits)
            details[rel] = hits
    return counts, details


def load_baseline(path=None):
    path = BASELINE if path is None else Path(path)
    if not path.exists():
        return {}
    return json.loads(path.read_text())


def write_baseline(counts):
    BASELINE.write_text(json.dumps(dict(sorted(
        (k, v) for k, v in counts.items() if v > 0)), indent=1) + "\n")


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--update-baseline", action="store_true",
                    help="lower recorded counts to match the tree; never raises one")
    ap.add_argument("--baseline", metavar="PATH",
                    help="check against this baseline instead of the committed one "
                         "(CI passes the base branch's copy)")
    args = ap.parse_args(argv)

    counts, details = scan_tree()
    baseline = load_baseline(args.baseline)

    if args.update_baseline:
        merged = {}
        raised = []
        for rel, n in counts.items():
            old = baseline.get(rel, 0)
            if n > old:
                raised.append((rel, old, n))
                merged[rel] = old
            else:
                merged[rel] = n
        write_baseline(merged)
        if raised:
            print("refused to raise the budget for:", file=sys.stderr)
            for rel, old, n in raised:
                print(f"  {rel}: {old} -> {n}", file=sys.stderr)
            return 1
        print(f"baseline updated: {sum(merged.values())} reference line(s) "
              f"across {sum(1 for v in merged.values() if v)} file(s)")
        return 0

    over = []
    for rel, n in counts.items():
        budget = baseline.get(rel, 0)
        if n > budget:
            over.append((rel, budget, n))
    for rel, budget, n in sorted(over):
        for line_no, text in details[rel][:5]:
            print(f"{rel}:{line_no}: {text}")
        print(f"  -> {rel}: {n} issue/PR reference(s) in comments, budget {budget}")
    if over:
        print(f"\n{len(over)} file(s) gained issue/PR references in comments. "
              "Explain the code in the comment or move the history to the PR body; "
              "after a genuine sweep, run `python3 scripts/lint_comment_refs.py "
              "--update-baseline`.", file=sys.stderr)
        return 1
    total = sum(counts.values())
    print(f"ok: {total} reference line(s) across {len(counts)} file(s), "
          f"none above its budget")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
