#!/usr/bin/env python3
"""Ratchet: issue and PR numbers do not belong in code comments.

The rule lives in `.claude/rules/comments.md`: a comment explains what the code
cannot say for itself, never where the code came from. A bare issue number in
a comment is a pointer into a tracker the source tree does not own, and it
rots the day the issue closes. History belongs in commit messages, PR bodies,
and `docs/design/`.

The tree carried thousands of these when the rule landed, so this is a
ratchet, not a ban switch: `lint_comment_refs_baseline.json` records the count
per file at the time each file was last swept, the lint fails only when a
file exceeds its recorded count, and `--update-baseline` may lower a count or
drop a file but never raise one. A file absent from the baseline has a budget
of zero. CI checks a pull request against the base branch's baseline, so a
baseline edit in the same PR cannot buy budget; a reviewer rejects any
baseline diff that raises a count. The baseline is regenerated by hand only
when the parser or its population changes (`write_baseline(scan_tree()[0])`
from a Python prompt), in the same PR, where the newly counted files are
visible in the diff.

Population: git-tracked C, C++, Objective-C++, shader, Lua, Python, shell,
PowerShell, Starlark, and CMake sources, plus every tracked extension-less
file whose first line names an interpreter. Vendored and generated trees are
skipped. Comments are found by a per-family tokenizer that steps over string
literals, character literals, raw strings, and block comments, so a
ticket-shaped value inside a string is never a hit.

Exit 0: no file exceeds its budget. Exit 1: at least one does, printed as
`file:line: <comment>`; the summary names the baseline command to run after a
genuine sweep.
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BASELINE = Path(__file__).resolve().with_name("lint_comment_refs_baseline.json")

SLASH_COMMENT_EXTS = {".hpp", ".cpp", ".h", ".hh", ".hxx", ".cc", ".cxx", ".c",
                      ".tpp", ".inl", ".mm", ".m", ".glsl", ".metal"}
PYTHON_EXTS = {".py"}
HASH_COMMENT_EXTS = {".sh", ".bash", ".zsh", ".ps1", ".cmake", ".bzl", ".bazel"}
DASH_COMMENT_EXTS = {".lua"}
HASH_COMMENT_NAMES = {"CMakeLists.txt"}
SKIP_PREFIXES = (
    "engine/render/third_party/",
    "engine/render/include/irreden/render/gl_wrap/",
    "third_party/",
    "build/",
    # The checker and its fixtures spell the pattern they detect.
    "scripts/lint_comment_refs.py",
    "scripts/fleet/tests/test_lint_comment_refs.py",
)
INTERPRETER_RE = re.compile(r"^#!.*\b(python\d*|bash|sh|zsh)\b")
REF_RE = re.compile(r"#\d{3,4}\b")
RAW_STRING_RE = re.compile(r'(?:u8|u|U|L)?R"([^\s()\\]{0,16})\(')


def tracked_files():
    out = subprocess.run(["git", "-C", str(REPO), "ls-files", "-z"],
                         capture_output=True, text=True, check=True).stdout
    return [p for p in out.split("\0") if p]


def comment_family(rel):
    """`slash`, `python`, `hash`, or `dash` for a file the ratchet covers,
    else None."""
    if rel.startswith(SKIP_PREFIXES):
        return None
    p = Path(rel)
    if p.suffix in SLASH_COMMENT_EXTS:
        return "slash"
    if p.suffix in PYTHON_EXTS:
        return "python"
    if p.suffix in HASH_COMMENT_EXTS or p.name in HASH_COMMENT_NAMES:
        return "hash"
    if p.suffix in DASH_COMMENT_EXTS:
        return "dash"
    if p.suffix == "" and not p.name.startswith("."):
        try:
            with open(REPO / rel, errors="replace") as f:
                first = f.readline()
        except OSError:
            return None
        if INTERPRETER_RE.match(first):
            return "python" if "python" in first else "hash"
    return None


def _skip_quoted(text, i, quote, escapes):
    """Index just past the string that opens at text[i] (a `quote` char).
    An unterminated string ends at the newline."""
    i += 1
    n = len(text)
    while i < n:
        ch = text[i]
        if ch == "\\" and escapes and i + 1 < n and text[i + 1] != "\n":
            i += 2
            continue
        if ch == quote:
            return i + 1
        if ch == "\n":
            return i
        i += 1
    return n


def _skip_to(text, i, terminator):
    end = text.find(terminator, i)
    return len(text) if end < 0 else end + len(terminator)


def _mask_slash(text):
    """C-family: `//` to end of line, `/* ... */` blocks; steps over string,
    character, and raw-string literals."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        two = text[i:i + 2]
        if two == "//":
            end = text.find("\n", i)
            end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif two == "/*":
            end = _skip_to(text, i, "*/")
            out.append(text[i:end])
            i = end
        elif ch in "RuUL" and (i == 0 or not _ident(text[i - 1])) \
                and RAW_STRING_RE.match(text, i):
            m = RAW_STRING_RE.match(text, i)
            end = _skip_to(text, m.end(), ")" + m.group(1) + '"')
            out.append(_blank(text[i:end]))
            i = end
        elif ch == '"':
            end = _skip_quoted(text, i, '"', True)
            out.append(_blank(text[i:end]))
            i = end
        elif ch == "'":
            end = _skip_quoted(text, i, "'", True)
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


def _mask_hash(text, python):
    """`#` to end of line. Python also has triple-quoted strings; shell-style
    single quotes take no escapes."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        if ch == "#":
            end = text.find("\n", i)
            end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif python and text[i:i + 3] in ('"""', "'''"):
            end = _skip_to(text, i + 3, text[i:i + 3])
            out.append(_blank(text[i:end]))
            i = end
        elif ch == '"':
            end = _skip_quoted(text, i, '"', True)
            out.append(_blank(text[i:end]))
            i = end
        elif ch == "'":
            end = _skip_quoted(text, i, "'", python)
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


_LUA_LONG_OPEN_RE = re.compile(r"\[(=*)\[")


def _mask_dash(text):
    """Lua: `--` to end of line, `--[=*[ ... ]=*]` blocks; steps over quoted
    strings and `[=*[ ... ]=*]` long strings."""
    out, i, n = [], 0, len(text)
    while i < n:
        ch = text[i]
        if text[i:i + 2] == "--":
            m = _LUA_LONG_OPEN_RE.match(text, i + 2)
            if m:
                end = _skip_to(text, m.end(), "]" + m.group(1) + "]")
            else:
                end = text.find("\n", i)
                end = n if end < 0 else end
            out.append(text[i:end])
            i = end
        elif ch == "[" and _LUA_LONG_OPEN_RE.match(text, i):
            m = _LUA_LONG_OPEN_RE.match(text, i)
            end = _skip_to(text, m.end(), "]" + m.group(1) + "]")
            out.append(_blank(text[i:end]))
            i = end
        elif ch in ('"', "'"):
            end = _skip_quoted(text, i, ch, True)
            out.append(_blank(text[i:end]))
            i = end
        else:
            out.append(" " if ch != "\n" else "\n")
            i += 1
    return "".join(out)


def _blank(s):
    return "".join("\n" if c == "\n" else " " for c in s)


def _ident(c):
    return c.isalnum() or c == "_"


def comment_mask(text, family):
    """`text` with every non-comment character replaced by a space; line
    structure is preserved so line numbers survive."""
    if family == "slash":
        return _mask_slash(text)
    if family == "python":
        return _mask_hash(text, python=True)
    if family == "hash":
        return _mask_hash(text, python=False)
    if family == "dash":
        return _mask_dash(text)
    raise ValueError(family)


def scan_text(text, family):
    """Lines whose comment portion carries an issue/PR reference, as
    `(line_no, stripped_line)`."""
    hits = []
    masked = comment_mask(text, family).split("\n")
    for n, (line, comment) in enumerate(zip(text.split("\n"), masked), 1):
        if REF_RE.search(comment):
            hits.append((n, line.strip()))
    return hits


def scan_file(rel, family):
    try:
        text = (REPO / rel).read_text(errors="replace")
    except OSError:
        return []
    return scan_text(text, family)


def scan_tree():
    counts, details = {}, {}
    for rel in tracked_files():
        family = comment_family(rel)
        if family is None:
            continue
        hits = scan_file(rel, family)
        if hits:
            counts[rel] = len(hits)
            details[rel] = hits
    return counts, details


def load_baseline(path=None):
    path = BASELINE if path is None else Path(path)
    if not path.exists():
        return {}
    return json.loads(path.read_text())


def write_baseline(counts):
    BASELINE.write_text(json.dumps(dict(sorted(
        (k, v) for k, v in counts.items() if v > 0)), indent=1) + "\n")


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--update-baseline", action="store_true",
                    help="lower recorded counts to match the tree; never raises one")
    ap.add_argument("--baseline", metavar="PATH",
                    help="check against this baseline instead of the committed one "
                         "(CI passes the base branch's copy)")
    args = ap.parse_args(argv)

    counts, details = scan_tree()
    baseline = load_baseline(args.baseline)

    if args.update_baseline:
        merged = {}
        raised = []
        for rel, n in counts.items():
            old = baseline.get(rel, 0)
            if n > old:
                raised.append((rel, old, n))
                merged[rel] = old
            else:
                merged[rel] = n
        write_baseline(merged)
        if raised:
            print("refused to raise the budget for:", file=sys.stderr)
            for rel, old, n in raised:
                print(f"  {rel}: {old} -> {n}", file=sys.stderr)
            return 1
        print(f"baseline updated: {sum(merged.values())} reference line(s) "
              f"across {sum(1 for v in merged.values() if v)} file(s)")
        return 0

    over = []
    for rel, n in counts.items():
        budget = baseline.get(rel, 0)
        if n > budget:
            over.append((rel, budget, n))
    for rel, budget, n in sorted(over):
        for line_no, text in details[rel][:5]:
            print(f"{rel}:{line_no}: {text}")
        print(f"  -> {rel}: {n} issue/PR reference(s) in comments, budget {budget}")
    if over:
        print(f"\n{len(over)} file(s) gained issue/PR references in comments. "
              "Explain the code in the comment or move the history to the PR body; "
              "after a genuine sweep, run `python3 scripts/lint_comment_refs.py "
              "--update-baseline`.", file=sys.stderr)
        return 1
    total = sum(counts.values())
    print(f"ok: {total} reference line(s) across {len(counts)} file(s), "
          f"none above its budget")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
