if(NOT DEFINED QUALITY_FILE_LIST OR QUALITY_FILE_LIST STREQUAL "")
    message(FATAL_ERROR "QUALITY_FILE_LIST is required.")
endif()
string(REPLACE "\"" "" QUALITY_FILE_LIST "${QUALITY_FILE_LIST}")

include("${QUALITY_FILE_LIST}")
if(NOT DEFINED QUALITY_FILES OR QUALITY_FILES STREQUAL "")
    message(FATAL_ERROR "QUALITY_FILES is empty. No files to check.")
endif()

# Headers that still carry banned namespace-scope mutable globals. Mirrors the
# `## Live deviations` section of .claude/rules/cpp-globals.md — the rule text
# and this executor are meant to name the same set, so update both together.
# Ratchet only: a file may leave this list, never join it.
set(header_global_baseline
    # Empty: lighting_demo_scene.hpp's 16 globals were migrated by #2726.
)

# Same ratchet, for the anonymous-namespace ban. GLAPITrace.h is generated by
# GetGLAPI.py and included by exactly one TU (engine/render/src/gl_wrap/
# GLAPITrace.cpp), so its file-scope `namespace { GL4API apiHook; }` is a real
# deviation but not a live ODR hazard (see #2815).
set(anonymous_namespace_baseline
    "engine/render/include/irreden/render/gl_wrap/GLAPITrace.h" # generated, single-TU, #2815
)

set(anonymous_namespace_failures "")
set(feature_detail_namespace_failures "")
set(header_global_failures "")
set(file_count 0)

# Runs the header-global reject chain against one already-joined declaration
# line and appends to `header_global_failures` (outer scope — macros don't
# get their own) when it survives every exemption. A macro rather than a
# function because the reject chain is a sequence of early-outs; CMake
# functions can't mutate the caller's list without an explicit PARENT_SCOPE
# round-trip, so the chain is expressed as `should_flag` guards instead of
# `continue()`/`return()`.
macro(irreden_process_header_global_candidate line_text)
    set(candidate_line "${line_text}")
    set(should_flag TRUE)

    # `extern "C" {` — a linkage block, not a variable.
    if(candidate_line MATCHES "^[ \t]*extern[ \t]+\"")
        set(should_flag FALSE)
    endif()

    if(should_flag)
        # Declaration head only — everything before the initializer or
        # terminator. A whole-line scan would read a trailing comment's
        # "const" as a qualifier and pass real globals as clean.
        string(REGEX REPLACE "[=;{].*$" "" decl_head "${candidate_line}")
        # `constexpr` always makes the declared object itself a constant.
        if(decl_head MATCHES "(^|[ \t])constexpr[ \t]")
            set(should_flag FALSE)
        endif()
    endif()

    if(should_flag)
        # Strip template argument lists before looking for a pointer
        # declarator — a `*` inside `<...>` belongs to a type argument
        # (`std::array<const char *, N>`), not to the declared object.
        # Repeated to unwrap nesting; CMake has no loop-until-stable.
        set(decl_core "${decl_head}")
        foreach(unused_pass RANGE 3)
            string(REGEX REPLACE "<[^<>]*>" "" decl_core "${decl_core}")
        endforeach()
        if(decl_core MATCHES "\\*")
            # A pointer declaration is a program constant only when BOTH
            # ends are const: `const T *const p`. A leading `const` alone
            # freezes the pointee (`const T *p` is a mutable pointer —
            # reseatable state), and a trailing `const` alone freezes the
            # pointer to still-mutable data. Either way it is unowned
            # process state, which is what this ban is about.
            if(decl_core MATCHES "(^|[ \t])const[ \t]" AND
               decl_core MATCHES "\\*[ \t]*const([ \t]|$)")
                set(should_flag FALSE)
            endif()
        elseif(decl_core MATCHES "(^|[ \t])const[ \t]")
            # Non-pointer `const` (incl. `extern const`, `inline static
            # const`) and `const T &` references are program constants.
            set(should_flag FALSE)
        endif()
    endif()

    if(should_flag)
        # A `(` before the initializer means a function declaration, which
        # is what the rule's `[^(]*` guard drops. (No separate `void`
        # reject: `inline void f() {}` is already caught here, and
        # `inline void *g_x = ...;` is a banned mutable pointer, not an
        # exemption.)
        if(candidate_line MATCHES "^[^;={]*\\(")
            set(should_flag FALSE)
        endif()
    endif()

    if(should_flag)
        # Safety net: a candidate flushed with no terminator at all (should
        # not happen — callers only flush on a matched terminator — kept as
        # a defensive guard against a future call site that doesn't).
        if(NOT candidate_line MATCHES "[;={]")
            set(should_flag FALSE)
        endif()
    endif()

    if(should_flag)
        string(STRIP "${candidate_line}" stripped_line)
        # Escape the source line's `;` — CMake lists are `;`-delimited, so
        # an unescaped one splits the entry and emits a blank bullet.
        string(REPLACE ";" "\\;" stripped_line "${stripped_line}")
        list(APPEND header_global_failures "${normalized_file_path}: ${stripped_line}")
    endif()
endmacro()

foreach(file_path IN LISTS QUALITY_FILES)
    file(TO_CMAKE_PATH "${file_path}" normalized_file_path)
    if(normalized_file_path MATCHES "/(build|_deps|third_party)/")
        continue()
    endif()
    if(NOT normalized_file_path MATCHES "\\.(h|hpp|inl)$")
        continue()
    endif()

    math(EXPR file_count "${file_count} + 1")
    file(READ "${normalized_file_path}" file_contents)

    set(is_anonymous_namespace_baselined FALSE)
    foreach(baselined IN LISTS anonymous_namespace_baseline)
        if(normalized_file_path MATCHES "/${baselined}$")
            set(is_anonymous_namespace_baselined TRUE)
            break()
        endif()
    endforeach()

    string(REGEX MATCH "(^|[\r\n])[ \t]*namespace[ \t\r\n]*\\{" has_anonymous_namespace "${file_contents}")
    if(has_anonymous_namespace AND NOT is_anonymous_namespace_baselined)
        list(APPEND anonymous_namespace_failures "${normalized_file_path}")
    endif()

    string(REGEX MATCH "namespace[ \t\r\n]+[A-Za-z_][A-Za-z0-9_]*Detail[ \t\r\n]*\\{" has_feature_detail_namespace "${file_contents}")
    if(has_feature_detail_namespace)
        list(APPEND feature_detail_namespace_failures "${normalized_file_path}")
    endif()

    # Header-global ban (.claude/rules/cpp-globals.md): no new mutable
    # namespace-scope `inline` / `extern` variable in a header. `constexpr` /
    # `const` are program constants and stay allowed, as do the module entry
    # points that declare the sanctioned manager globals.
    set(is_baselined FALSE)
    foreach(baselined IN LISTS header_global_baseline)
        if(normalized_file_path MATCHES "/${baselined}$")
            set(is_baselined TRUE)
            break()
        endif()
    endforeach()
    # engine/<module>/include/irreden/ir_<module>.hpp + engine/include/irreden/ir_engine.hpp
    if(normalized_file_path MATCHES "/engine/([^/]+/)?include/irreden/ir_[^/]+\\.hpp$")
        set(is_baselined TRUE)
    endif()

    if(NOT is_baselined)
        # CMake's regex engine has no lookahead, so the rule's negative
        # assertions are applied as per-line rejects in
        # irreden_process_header_global_candidate() rather than inline.
        #
        # Read every line unfiltered (not REGEX-filtered) so a candidate whose
        # terminator wraps onto a continuation line — exactly what the repo's
        # own 100-col clang-format produces on a long `inline` declaration —
        # can be joined back into one line before the reject chain runs.
        # `file(STRINGS ... REGEX ...)` would have already discarded that
        # continuation line, since it doesn't itself start with
        # `inline`/`extern`.
        #
        # Single forward pass over the lines, not index-by-index `list(GET)`
        # — that call is a linear scan of the list per invocation, so an
        # index loop over an n-line file costs O(n^2) overall, dominated by
        # whichever header in the tree has the most lines. `join_pending`/
        # `join_buffer` below carry the in-progress join instead of
        # re-deriving the next index.
        file(STRINGS "${normalized_file_path}" all_lines)

        set(join_pending FALSE)
        set(join_buffer "")
        set(join_steps 0)
        # Bounded lookahead so a candidate that never terminates (or a
        # runaway match) can't scan the rest of the file; a real declaration
        # wrap is one or two lines.
        set(max_join_lookahead_lines 10)

        foreach(raw_line IN LISTS all_lines)
            # Strip a trailing line comment before it can reach either the
            # terminator test or the function-declaration guard inside the
            # macro — a `(` inside explanatory comment text on a wrapped
            # declaration's head line otherwise reads as a function
            # signature and the declaration silently exempts itself.
            string(REGEX REPLACE "//.*$" "" stripped_raw_line "${raw_line}")

            if(join_pending)
                string(APPEND join_buffer " ${stripped_raw_line}")
                math(EXPR join_steps "${join_steps} + 1")
                if(join_buffer MATCHES "[;={]")
                    irreden_process_header_global_candidate("${join_buffer}")
                    set(join_pending FALSE)
                    set(join_buffer "")
                    set(join_steps 0)
                elseif(join_steps GREATER_EQUAL max_join_lookahead_lines)
                    # Lookahead exhausted with no terminator (genuinely
                    # multi-line signature, or EOF next) — drop the
                    # candidate rather than flag on partial text.
                    set(join_pending FALSE)
                    set(join_buffer "")
                    set(join_steps 0)
                endif()
                continue()
            endif()

            if(NOT stripped_raw_line MATCHES "^[ \t]*(inline|extern)[ \t]")
                continue()
            endif()

            if(stripped_raw_line MATCHES "[;={]")
                irreden_process_header_global_candidate("${stripped_raw_line}")
            else()
                set(join_pending TRUE)
                set(join_buffer "${stripped_raw_line}")
                set(join_steps 0)
            endif()
        endforeach()
        # A join still pending here ran out of lines (EOF) before finding a
        # terminator or hitting the lookahead bound — same drop as the
        # bounded-exhaustion case above, nothing left to flush.
    endif()
endforeach()

list(LENGTH header_global_baseline header_global_baseline_count)
list(LENGTH anonymous_namespace_baseline anonymous_namespace_baseline_count)
message(STATUS
    "Header convention checks scanned ${file_count} header file(s); "
    "${header_global_baseline_count} file(s) baselined for header-global violations, "
    "${anonymous_namespace_baseline_count} for anonymous namespaces."
)

if(anonymous_namespace_failures)
    list(JOIN anonymous_namespace_failures "\n  - " anonymous_namespace_failures_joined)
    message(FATAL_ERROR
        "Anonymous namespaces are not allowed in headers. Use a nested `detail` namespace "
        "or move the implementation to a .cpp file.\n"
        "  - ${anonymous_namespace_failures_joined}"
    )
endif()

if(feature_detail_namespace_failures)
    list(JOIN feature_detail_namespace_failures "\n  - " feature_detail_namespace_failures_joined)
    message(FATAL_ERROR
        "Feature-specific `*Detail` namespaces are not allowed in headers. Prefer the "
        "nested lowercase `detail` convention unless the helper namespace is an intentional "
        "shared submodule.\n"
        "  - ${feature_detail_namespace_failures_joined}"
    )
endif()

if(header_global_failures)
    list(JOIN header_global_failures "\n  - " header_global_failures_joined)
    message(FATAL_ERROR
        "Mutable namespace-scope globals are not allowed in headers. Every process- or "
        "world-scoped mutable object needs an owner, a lifecycle, and an accessor; route "
        "this one to the pattern that fits its state kind (see the table in "
        ".claude/rules/cpp-globals.md). `constexpr` / `const` constants stay allowed.\n"
        "  - ${header_global_failures_joined}"
    )
endif()
